swagger: "2.0"
info:
  title: Generated Flask Server
  description: Example Generating Flask Server From Swagger YAML
  version: 1.0.0

paths:
  '/api/celebrity':
    get:
      operationId: api.get_celebrities
      responses:
        200:
          description: Response to "get all" celebrity query
    post:
      operationId: api.create_celebrity
      parameters:
        - in: body
          name: celebrity
          description: New celebrity
          schema:
            type: object
            required:
              - name
                pay
                year
                category
            properties:
              name:
                type: string
              pay:
                type: number
              year:
                type: integer
              category:
                type: string
      responses:
        200:
          description: Response to a new celebrity operation
        400:
          description: Must supply an object with a name, pay (number), year (integer), and category.

  '/api/celebrity/{name}':
    get:
      operationId: api.get_celebrity
      parameters:
        - name: name
          description: Celebrity name
          in: path
          type: string
          required: true
      responses:
        200:
          description: Response to a single celebrity query
          schema:
            type: object
            properties:
              names:
                type: array
        400:
          description: Invalid URL, perhaps?
        404:
          description: No celebrity with that name.
        default:
          description: Unexpected error.
    put:
      operationId: api.put_celebrity
      parameters:
        - name: name
          description: Celebrity name
          in: path
          type: string
          required: true
        - in: body
          name: celebrity
          description: New celebrity
          schema:
            type: object
            properties:
              pay:
                type: number
              year:
                type: integer
              category:
                type: string
      responses:
        200:
          description: Response to a single celebrity update
          schema:
            type: object
            properties:
              message:
                type: string
              status:
                type: integer
        400:
          description: Invalid URL, perhaps?
        404:
          description: No celebrity with that name.
        default:
          description: Unexpected error.
    delete:
      operationId: api.delete_celebrity
      parameters:
        - name: name
          description: Celebrity name
          in: path
          type: string
          required: true
      responses:
        200:
          description: Response to a single celebrity update
          schema:
            type: object
            properties:
              message:
                type: string
              status:
                type: integer
        400:
          description: Invalid URL, perhaps?
        404:
          description: No celebrity with that name.
        default:
          description: Unexpected error.